export default data = () => {
//     "All_air_pages": [
//         {
//             "Page": "MasterScreen",
//             "Section": "Country",
//             "Seq. No": "1",
//             "Field Name": "Country Code",
//             "Data Type": "Text",
//             "Tooltip": "ISO Country Code",
//             "Prompt": "Enter ISO Country Code",
//             "Requires Sorting": "Yes",
//             "List of Value (Refer from Parent Screen)": ""
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Country",
//             "Seq. No": "2",
//             "Field Name": "Country Name",
//             "Data Type": "Text",
//             "Tooltip": "Full Country Name",
//             "Prompt": "Enter Country Name",
//             "Requires Sorting": "Yes",
//             "List of Value (Refer from Parent Screen)": ""
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Country",
//             "Seq. No": "3",
//             "Field Name": "Continent",
//             "Data Type": "Dropdown",
//             "Tooltip": "Continent the Country Belongs",
//             "Prompt": "Select Continent",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": ""
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Country",
//             "Seq. No": "4",
//             "Field Name": "Air Logistics Availability",
//             "Data Type": "Checkbox",
//             "Tooltip": "Air Logistics Support",
//             "Prompt": "Check if Available",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": ""
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Country",
//             "Seq. No": "5",
//             "Field Name": "Sea Logistics Availability",
//             "Data Type": "Checkbox",
//             "Tooltip": "Sea Logistics Support",
//             "Prompt": "Check if Available",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": ""
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Country",
//             "Seq. No": "6",
//             "Field Name": "Import Regulations",
//             "Data Type": "Text",
//             "Tooltip": "Import Rules and Regulations",
//             "Prompt": "Enter Import Rules",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": ""
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Country",
//             "Seq. No": "7",
//             "Field Name": "Export Regulations",
//             "Data Type": "Text",
//             "Tooltip": "Export Rules and Regulations",
//             "Prompt": "Enter Export Rules",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": ""
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Country",
//             "Seq. No": "8",
//             "Field Name": "Customs Information",
//             "Data Type": "Text",
//             "Tooltip": "Customs Procedures",
//             "Prompt": "Enter Customs Info",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": ""
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Destination",
//             "Seq. No": "1",
//             "Field Name": "Destination Code",
//             "Data Type": "Text",
//             "Tooltip": "ISO Destination Code",
//             "Prompt": "Enter ISO Code",
//             "Requires Sorting": "Yes",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Destination",
//             "Seq. No": "2",
//             "Field Name": "Destination Name",
//             "Data Type": "Text",
//             "Tooltip": "Full Destination Name",
//             "Prompt": "Enter Destination Name",
//             "Requires Sorting": "Yes",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Destination",
//             "Seq. No": "3",
//             "Field Name": "Continent",
//             "Data Type": "Dropdown",
//             "Tooltip": "Continent the Destination Belongs To",
//             "Prompt": "Select Continent",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "Continent List"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Destination",
//             "Seq. No": "4",
//             "Field Name": "Country",
//             "Data Type": "Dropdown",
//             "Tooltip": "Country the Destination is In",
//             "Prompt": "Select Country",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "Country List"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Destination",
//             "Seq. No": "5",
//             "Field Name": "Air Logistics Availability",
//             "Data Type": "Checkbox",
//             "Tooltip": "Air Logistics Support",
//             "Prompt": "Check if Available",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Destination",
//             "Seq. No": "6",
//             "Field Name": "Sea Logistics Availability",
//             "Data Type": "Checkbox",
//             "Tooltip": "Sea Logistics Support",
//             "Prompt": "Check if Available",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Destination",
//             "Seq. No": "7",
//             "Field Name": "Port Information",
//             "Data Type": "Text",
//             "Tooltip": "Information about Port",
//             "Prompt": "Enter Port Info",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Destination",
//             "Seq. No": "8",
//             "Field Name": "Customs Information",
//             "Data Type": "Text",
//             "Tooltip": "Customs Procedures",
//             "Prompt": "Enter Customs Info",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Freight Type",
//             "Seq. No": "1",
//             "Field Name": "Freight Type Code",
//             "Data Type": "Text",
//             "Tooltip": "Unique Code for Freight Type",
//             "Prompt": "Enter Freight Code",
//             "Requires Sorting": "Yes",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Freight Type",
//             "Seq. No": "2",
//             "Field Name": "Freight Type Name",
//             "Data Type": "Text",
//             "Tooltip": "Name of the Freight Type",
//             "Prompt": "Enter Freight Name",
//             "Requires Sorting": "Yes",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Freight Type",
//             "Seq. No": "3",
//             "Field Name": "Description",
//             "Data Type": "Text",
//             "Tooltip": "Description of Freight Type",
//             "Prompt": "Enter Description",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Freight Type",
//             "Seq. No": "4",
//             "Field Name": "Air Logistics Compatibility",
//             "Data Type": "Checkbox",
//             "Tooltip": "Compatibility with Air Logistics",
//             "Prompt": "Check if Compatible",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Freight Type",
//             "Seq. No": "5",
//             "Field Name": "Sea Logistics Compatibility",
//             "Data Type": "Checkbox",
//             "Tooltip": "Compatibility with Sea Logistics",
//             "Prompt": "Check if Compatible",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Freight Type",
//             "Seq. No": "6",
//             "Field Name": "Weight Limit",
//             "Data Type": "Number",
//             "Tooltip": "Maximum Weight Limit",
//             "Prompt": "Enter Weight Limit",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Freight Type",
//             "Seq. No": "7",
//             "Field Name": "Volume Limit",
//             "Data Type": "Number",
//             "Tooltip": "Maximum Volume Limit",
//             "Prompt": "Enter Volume Limit",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Freight Type",
//             "Seq. No": "8",
//             "Field Name": "Special Requirements",
//             "Data Type": "Text",
//             "Tooltip": "Any Special Handling or Requirements",
//             "Prompt": "Enter Requirements",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Carrier List",
//             "Seq. No": "1",
//             "Field Name": "Carrier Code",
//             "Data Type": "Text",
//             "Tooltip": "Unique Code for Carrier",
//             "Prompt": "Enter Carrier Code",
//             "Requires Sorting": "Yes",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Carrier List",
//             "Seq. No": "2",
//             "Field Name": "Carrier Name",
//             "Data Type": "Text",
//             "Tooltip": "Name of the Carrier",
//             "Prompt": "Enter Carrier Name",
//             "Requires Sorting": "Yes",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Carrier List",
//             "Seq. No": "3",
//             "Field Name": "Service Type",
//             "Data Type": "Dropdown",
//             "Tooltip": "Type of Service Provided",
//             "Prompt": "Select Service Type",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "Air, Sea, Both"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Carrier List",
//             "Seq. No": "4",
//             "Field Name": "Headquarters",
//             "Data Type": "Text",
//             "Tooltip": "Location of Headquarters",
//             "Prompt": "Enter Location",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Carrier List",
//             "Seq. No": "5",
//             "Field Name": "Contact Number",
//             "Data Type": "Text",
//             "Tooltip": "Carrier Contact Number",
//             "Prompt": "Enter Contact Number",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Carrier List",
//             "Seq. No": "6",
//             "Field Name": "Email Address",
//             "Data Type": "Text",
//             "Tooltip": "Carrier Email Address",
//             "Prompt": "Enter Email Address",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Carrier List",
//             "Seq. No": "7",
//             "Field Name": "Air Logistics Compatibility",
//             "Data Type": "Checkbox",
//             "Tooltip": "Compatibility with Air Logistics",
//             "Prompt": "Check if Compatible",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Carrier List",
//             "Seq. No": "8",
//             "Field Name": "Sea Logistics Compatibility",
//             "Data Type": "Checkbox",
//             "Tooltip": "Compatibility with Sea Logistics",
//             "Prompt": "Check if Compatible",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Carrier List",
//             "Seq. No": "9",
//             "Field Name": "Special Features",
//             "Data Type": "Text",
//             "Tooltip": "Any Special Features or Services",
//             "Prompt": "Enter Features",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Carrier List",
//             "Seq. No": "10",
//             "Field Name": "Limitations",
//             "Data Type": "Text",
//             "Tooltip": "Any Limitations or Restrictions",
//             "Prompt": "Enter Limitations",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Cargo Type ",
//             "Seq. No": "1",
//             "Field Name": "Cargo Type Code",
//             "Data Type": "Text",
//             "Tooltip": "Unique Code for Cargo Type",
//             "Prompt": "Enter Cargo Code",
//             "Requires Sorting": "Yes",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Cargo Type ",
//             "Seq. No": "2",
//             "Field Name": "Cargo Type Name",
//             "Data Type": "Text",
//             "Tooltip": "Name of the Cargo Type",
//             "Prompt": "Enter Cargo Name",
//             "Requires Sorting": "Yes",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Cargo Type ",
//             "Seq. No": "3",
//             "Field Name": "Description",
//             "Data Type": "Text",
//             "Tooltip": "Description of Cargo Type",
//             "Prompt": "Enter Description",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Cargo Type ",
//             "Seq. No": "4",
//             "Field Name": "Air Logistics Compatibility",
//             "Data Type": "Checkbox",
//             "Tooltip": "Compatibility with Air Logistics",
//             "Prompt": "Check if Compatible",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Cargo Type ",
//             "Seq. No": "5",
//             "Field Name": "Sea Logistics Compatibility",
//             "Data Type": "Checkbox",
//             "Tooltip": "Compatibility with Sea Logistics",
//             "Prompt": "Check if Compatible",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Cargo Type ",
//             "Seq. No": "6",
//             "Field Name": "Weight Limit",
//             "Data Type": "Number",
//             "Tooltip": "Maximum Weight Limit",
//             "Prompt": "Enter Weight Limit",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Cargo Type ",
//             "Seq. No": "7",
//             "Field Name": "Volume Limit",
//             "Data Type": "Number",
//             "Tooltip": "Maximum Volume Limit",
//             "Prompt": "Enter Volume Limit",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Cargo Type ",
//             "Seq. No": "8",
//             "Field Name": "Special Requirements",
//             "Data Type": "Text",
//             "Tooltip": "Any Special Handling or Requirements",
//             "Prompt": "Enter Requirements",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Packaging Type",
//             "Seq. No": "1",
//             "Field Name": "Packaging Type Code",
//             "Data Type": "Text",
//             "Tooltip": "Unique Code for Packaging",
//             "Prompt": "Enter Packaging Code",
//             "Requires Sorting": "Yes",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Packaging Type",
//             "Seq. No": "2",
//             "Field Name": "Packaging Type Name",
//             "Data Type": "Text",
//             "Tooltip": "Name of the Packaging Type",
//             "Prompt": "Enter Packaging Name",
//             "Requires Sorting": "Yes",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Packaging Type",
//             "Seq. No": "3",
//             "Field Name": "Description",
//             "Data Type": "Text",
//             "Tooltip": "Description of Packaging",
//             "Prompt": "Enter Description",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Packaging Type",
//             "Seq. No": "4",
//             "Field Name": "Air Logistics Compatibility",
//             "Data Type": "Checkbox",
//             "Tooltip": "Compatibility with Air Logistics",
//             "Prompt": "Check if Compatible",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Packaging Type",
//             "Seq. No": "5",
//             "Field Name": "Sea Logistics Compatibility",
//             "Data Type": "Checkbox",
//             "Tooltip": "Compatibility with Sea Logistics",
//             "Prompt": "Check if Compatible",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Packaging Type",
//             "Seq. No": "6",
//             "Field Name": "Weight Limit",
//             "Data Type": "Number",
//             "Tooltip": "Maximum Weight Limit",
//             "Prompt": "Enter Weight Limit",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Packaging Type",
//             "Seq. No": "7",
//             "Field Name": "Volume Limit",
//             "Data Type": "Number",
//             "Tooltip": "Maximum Volume Limit",
//             "Prompt": "Enter Volume Limit",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Packaging Type",
//             "Seq. No": "8",
//             "Field Name": "Material",
//             "Data Type": "Text",
//             "Tooltip": "Material of Packaging",
//             "Prompt": "Enter Material",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         },
//         {
//             "Page": "MasterScreen",
//             "Section": "Packaging Type",
//             "Seq. No": "9",
//             "Field Name": "Special Requirements",
//             "Data Type": "Text",
//             "Tooltip": "Any Special Requirements",
//             "Prompt": "Enter Requirements",
//             "Requires Sorting": "No",
//             "List of Value (Refer from Parent Screen)": "N/A"
//         }
    // ]
};