export default data = () => {
    "Booking Confirmation and Payment - Sheet3": [
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Transaction group",
            "Field Name": "Booking ID",
            "Validate": "Mandatory",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Unique identifier for the booking",
            "Prompt": "Enter Booking ID"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Transaction group",
            "Field Name": "Booking Confirmation Number",
            "Validate": "Mandatory",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Unique identifier for the booking confirmation",
            "Prompt": "Enter the booking confirmation number"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Transaction group",
            "Field Name": "Confirmation Status",
            "Validate": "Mandatory",
            "Data Type": "Dropdown",
            "Parent Form": "Confirmed, Pending, Cancelled",
            "Field_Needed?": "Yes",
            "Tooltip": "Status of the booking confirmation",
            "Prompt": "Select Confirmation Status"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Transaction group",
            "Field Name": "Payment Status",
            "Validate": "Mandatory",
            "Data Type": "Dropdown",
            "Parent Form": "Paid, Unpaid, Partial",
            "Field_Needed?": "Yes",
            "Tooltip": "Status of the payment",
            "Prompt": "Select Payment Status"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Transaction group",
            "Field Name": "Invoice Number",
            "Validate": "Mandatory",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Unique identifier for the invoice",
            "Prompt": "Enter Invoice Number"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Transaction group",
            "Field Name": "Amount Due",
            "Validate": "Mandatory",
            "Data Type": "Number",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Total amount due for payment",
            "Prompt": "Enter Amount Due"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Transaction group",
            "Field Name": "Vessel Name",
            "Validate": "Mandatory",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Name of the vessel that will be transporting the goods",
            "Prompt": "Enter the vessel name"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Transaction group",
            "Field Name": "Voyage Number",
            "Validate": "Mandatory",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Unique identifier for the voyage",
            "Prompt": "Enter the voyage number"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Transaction group",
            "Field Name": "Port of Loading",
            "Validate": "Mandatory",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Port where the goods will be loaded onto the vessel",
            "Prompt": "Enter the port of loading"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Transaction group",
            "Field Name": "Port of Discharge",
            "Validate": "Mandatory",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Port where the goods will be unloaded from the vessel",
            "Prompt": "Enter the port of discharge"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Transaction group",
            "Field Name": "ETA (Estimated Time of Arrival)",
            "Validate": "Mandatory",
            "Data Type": "Date",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Estimated date and time of arrival at the port of discharge",
            "Prompt": "Enter the ETA"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Transaction group",
            "Field Name": "Payment Terms",
            "Validate": "Optional",
            "Data Type": "Dropdown",
            "Parent Form": "Net 30, Net 60, Due on Receipt",
            "Field_Needed?": "Yes",
            "Tooltip": "Terms for the payment",
            "Prompt": "Select Payment Terms"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Transaction group",
            "Field Name": "Order Confirmation",
            "Validate": "Optional",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Confirmation for the order",
            "Prompt": "Enter Order Confirmation"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Transaction group",
            "Field Name": "Payment Method",
            "Validate": "Mandatory",
            "Data Type": "Dropdown",
            "Parent Form": "Bank Transfer, Wire Transfer, Check, Credit Card",
            "Field_Needed?": "Yes",
            "Tooltip": "Select the payment method that will be used to pay for the booking",
            "Prompt": "Select the payment method"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Freight Forwarder",
            "Validate": "Mandatory",
            "Data Type": "Dropdown",
            "Parent Form": "List of Freight Forwarders",
            "Field_Needed?": "Yes",
            "Tooltip": "Freight forwarder handling the shipment",
            "Prompt": "Select Freight Forwarder"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Freight Forwarder Name",
            "Validate": "Mandatory",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Name of the freight forwarder responsible for the booking",
            "Prompt": "Enter the freight forwarder name"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Freight Forwarder Contact Information",
            "Validate": "Mandatory",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Contact information for the freight forwarder",
            "Prompt": "Enter the freight forwarder contact information"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Shipping Company",
            "Validate": "Mandatory",
            "Data Type": "Dropdown",
            "Parent Form": "List of Shipping Companies",
            "Field_Needed?": "Yes",
            "Tooltip": "Shipping company responsible for transport",
            "Prompt": "Select Shipping Company"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Shipping Company Name",
            "Validate": "Mandatory",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Name of the shipping company that will be transporting the goods",
            "Prompt": "Enter the shipping company name"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Shipping Company Contact Information",
            "Validate": "Mandatory",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Contact information for the shipping company",
            "Prompt": "Enter the shipping company contact information"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Mode of Transport",
            "Validate": "Mandatory",
            "Data Type": "Dropdown",
            "Parent Form": "Air, Sea, Rail, Road",
            "Field_Needed?": "Yes",
            "Tooltip": "Mode of transport for the shipment",
            "Prompt": "Select Mode of Transport"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Mode of Transportation",
            "Validate": "Mandatory",
            "Data Type": "Dropdown",
            "Parent Form": "Ocean, Air, Rail",
            "Field_Needed?": "Yes",
            "Tooltip": "Select the mode of transportation",
            "Prompt": "Select the mode of transportation"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Import/Export",
            "Validate": "Mandatory",
            "Data Type": "Dropdown",
            "Parent Form": "Import, Export",
            "Field_Needed?": "Yes",
            "Tooltip": "Type of logistics operation",
            "Prompt": "Select Import/Export"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Port of Origin",
            "Validate": "Optional",
            "Data Type": "Dropdown",
            "Parent Form": "List of Ports",
            "Field_Needed?": "Yes",
            "Tooltip": "Port where the shipment originates",
            "Prompt": "Select Port of Origin"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Port of Destination",
            "Validate": "Optional",
            "Data Type": "Dropdown",
            "Parent Form": "List of Ports",
            "Field_Needed?": "Yes",
            "Tooltip": "Port where the shipment will be delivered",
            "Prompt": "Select Port of Destination"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Estimated Time of Departure",
            "Validate": "Optional",
            "Data Type": "Date",
            "Parent Form": "N/A",
            "Field_Needed?": "No",
            "Tooltip": "Estimated time of shipment departure",
            "Prompt": "Enter Estimated Time of Departure"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Estimated Time of Arrival",
            "Validate": "Optional",
            "Data Type": "Date",
            "Parent Form": "N/A",
            "Field_Needed?": "No",
            "Tooltip": "Estimated time of shipment arrival",
            "Prompt": "Enter Estimated Time of Arrival"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Container Type",
            "Validate": "Optional",
            "Data Type": "Dropdown",
            "Parent Form": "20ft Dry, 40ft Dry, 40ft HC, Reefer, Flat Rack, Open Top",
            "Field_Needed?": "No",
            "Tooltip": "Select the type of container",
            "Prompt": "Select the container type (optional)"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "Logistics group",
            "Field Name": "Container Number (optional)",
            "Validate": "Optional",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "No",
            "Tooltip": "Enter the container number",
            "Prompt": "Enter the container number (optional)"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "User Interaction group",
            "Field Name": "Customer Name",
            "Validate": "Mandatory",
            "Data Type": "Dropdown",
            "Parent Form": "List of Customers",
            "Field_Needed?": "Yes",
            "Tooltip": "Name of the customer involved in the booking",
            "Prompt": "Select Customer"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "User Interaction group",
            "Field Name": "Customer Name",
            "Validate": "Mandatory",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Name of the customer booking the shipment",
            "Prompt": "Enter your name"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "User Interaction group",
            "Field Name": "Contact Email",
            "Validate": "Mandatory",
            "Data Type": "Email",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Email address for communication",
            "Prompt": "Enter Contact Email"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "User Interaction group",
            "Field Name": "Customer Email Address",
            "Validate": "Mandatory",
            "Data Type": "Email",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Email address of the customer",
            "Prompt": "Enter your email address"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "User Interaction group",
            "Field Name": "Contact Number",
            "Validate": "Mandatory",
            "Data Type": "Number",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Contact number for communication",
            "Prompt": "Enter Contact Number"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "User Interaction group",
            "Field Name": "Customer Phone Number",
            "Validate": "Mandatory",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Phone number of the customer",
            "Prompt": "Enter your phone number"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "User Interaction group",
            "Field Name": "Billing Address",
            "Validate": "Mandatory",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "Yes",
            "Tooltip": "Billing address of the customer",
            "Prompt": "Enter your billing address"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "User Interaction group",
            "Field Name": "Payment Method",
            "Validate": "Mandatory",
            "Data Type": "Dropdown",
            "Parent Form": "Credit Card, Bank Transfer, PayPal",
            "Field_Needed?": "Yes",
            "Tooltip": "Method of payment for the booking",
            "Prompt": "Select Payment Method"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "User Interaction group",
            "Field Name": "Shipping Address",
            "Validate": "Optional",
            "Data Type": "Text",
            "Parent Form": "N/A",
            "Field_Needed?": "No",
            "Tooltip": "Shipping address of the customer",
            "Prompt": "Enter your shipping address (optional)"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "User Interaction group",
            "Field Name": "Confirmation Status",
            "Validate": "Optional",
            "Data Type": "Text",
            "Parent Form": "Confirmed, Pending, Cancelled",
            "Field_Needed?": "No",
            "Tooltip": "Current status of the booking",
            "Prompt": "View Confirmation Status"
        },
        {
            "Page No": "",
            "Page": "Booking Confirmation and Payment",
            "Section": "User Interaction group",
            "Field Name": "Special Instructions",
            "Validate": "Optional",
            "Data Type": "Text Area",
            "Parent Form": "N/A",
            "Field_Needed?": "No",
            "Tooltip": "Any special instructions for the booking",
            "Prompt": "Enter Special Instructions"
        }
    ]
};