const database = {
  Additional_Services: [
    {
      Insurance: true,
      "Expedited Delivery": false,
      None: false,
      "Insurance Coverage": "Full Coverage",
      "Special Handling": "Fragile",
      "Storage Options": "Short-term",
      "Customs Clearance Assistance": true,
      "Cargo Tracking Service": true,
    },
    {
      Insurance: false,
      "Expedited Delivery": true,
      None: false,
      "Insurance Coverage": "Partial Coverage",
      "Special Handling": "Temperature-sensitive",
      "Storage Options": "Long-term",
      "Customs Clearance Assistance": false,
      "Cargo Tracking Service": true,
    },
    {
      Insurance: false,
      "Expedited Delivery": false,
      None: true,
      "Insurance Coverage": "N/A",
      "Special Handling": "N/A",
      "Storage Options": "N/A",
      "Customs Clearance Assistance": false,
      "Cargo Tracking Service": false,
    },
    {
      Insurance: true,
      "Expedited Delivery": true,
      None: false,
      "Insurance Coverage": "Full Coverage",
      "Special Handling": "Fragile",
      "Storage Options": "Short-term",
      "Customs Clearance Assistance": true,
      "Cargo Tracking Service": false,
    },
    {
      Insurance: false,
      "Expedited Delivery": false,
      None: true,
      "Insurance Coverage": "N/A",
      "Special Handling": "N/A",
      "Storage Options": "N/A",
      "Customs Clearance Assistance": false,
      "Cargo Tracking Service": false,
    },
    {
      Insurance: true,
      "Expedited Delivery": false,
      None: false,
      "Insurance Coverage": "Partial Coverage",
      "Special Handling": "Temperature-sensitive",
      "Storage Options": "Long-term",
      "Customs Clearance Assistance": true,
      "Cargo Tracking Service": true,
    },
    {
      Insurance: false,
      "Expedited Delivery": true,
      None: false,
      "Insurance Coverage": "Full Coverage",
      "Special Handling": "Fragile",
      "Storage Options": "Short-term",
      "Customs Clearance Assistance": false,
      "Cargo Tracking Service": true,
    },
    {
      Insurance: true,
      "Expedited Delivery": false,
      None: false,
      "Insurance Coverage": "Partial Coverage",
      "Special Handling": "Temperature-sensitive",
      "Storage Options": "Long-term",
      "Customs Clearance Assistance": true,
      "Cargo Tracking Service": false,
    },
    {
      Insurance: false,
      "Expedited Delivery": true,
      None: false,
      "Insurance Coverage": "Full Coverage",
      "Special Handling": "Fragile",
      "Storage Options": "Short-term",
      "Customs Clearance Assistance": true,
      "Cargo Tracking Service": true,
    },
  ],
  Cargo_Information: [
    {
      Weight: "2000 kg",
      Dimensions: "10x10x10 cm",
      Description: "Electronics",
      "Cargo Type": "Electronics",
      "Special Handling Instructions": "Handle with care",
      "Packaging Type": "Pallet",
      "Cargo Value": "$5000",
      "Temperature Requirements": "20°C - 25°C",
      "Fragile Indicator": "Yes",
      "Cargo Insurance": "Policy #12345",
      "Cargo Temperature Requirements": "15°C - 20°C",
      "Cargo Labeling Requirements": "Fragile",
      "Cargo Packaging Requirements": "Sealed Box",
    },
    {
      Weight: "1500 kg",
      Dimensions: "15x15x15 cm",
      Description: "Furniture",
      "Cargo Type": "Household",
      "Special Handling Instructions": "None",
      "Packaging Type": "Box",
      "Cargo Value": "$3000",
      "Temperature Requirements": "Room Temperature",
      "Fragile Indicator": "No",
      "Cargo Insurance": "Policy #12346",
      "Cargo Temperature Requirements": "N/A",
      "Cargo Labeling Requirements": "Heavy",
      "Cargo Packaging Requirements": "Wooden Crate",
    },
    {
      Weight: "1000 kg",
      Dimensions: "5x5x5 cm",
      Description: "Clothing",
      "Cargo Type": "Apparel",
      "Special Handling Instructions": "Fragile",
      "Packaging Type": "Crate",
      "Cargo Value": "$2000",
      "Temperature Requirements": "N/A",
      "Fragile Indicator": "Yes",
      "Cargo Insurance": "Policy #12347",
      "Cargo Temperature Requirements": "N/A",
      "Cargo Labeling Requirements": "Handle with care",
      "Cargo Packaging Requirements": "Cardboard Box",
    },
    {
      Weight: "2500 kg",
      Dimensions: "20x20x20 cm",
      Description: "Machinery",
      "Cargo Type": "Industrial",
      "Special Handling Instructions": "Handle with care",
      "Packaging Type": "Pallet",
      "Cargo Value": "$10000",
      "Temperature Requirements": "N/A",
      "Fragile Indicator": "No",
      "Cargo Insurance": "Policy #12348",
      "Cargo Temperature Requirements": "N/A",
      "Cargo Labeling Requirements": "Heavy",
      "Cargo Packaging Requirements": "Metal Crate",
    },
    {
      Weight: "3000 kg",
      Dimensions: "25x25x25 cm",
      Description: "Food",
      "Cargo Type": "Perishable",
      "Special Handling Instructions": "Keep Frozen",
      "Packaging Type": "Box",
      "Cargo Value": "$4000",
      "Temperature Requirements": "-18°C",
      "Fragile Indicator": "No",
      "Cargo Insurance": "Policy #12349",
      "Cargo Temperature Requirements": "-18°C",
      "Cargo Labeling Requirements": "Perishable",
      "Cargo Packaging Requirements": "Insulated Box",
    },
    {
      Weight: "3500 kg",
      Dimensions: "30x30x30 cm",
      Description: "Books",
      "Cargo Type": "Printed Material",
      "Special Handling Instructions": "None",
      "Packaging Type": "Crate",
      "Cargo Value": "$1000",
      "Temperature Requirements": "Room Temperature",
      "Fragile Indicator": "No",
      "Cargo Insurance": "Policy #12350",
      "Cargo Temperature Requirements": "N/A",
      "Cargo Labeling Requirements": "N/A",
      "Cargo Packaging Requirements": "Cardboard Box",
    },
    {
      Weight: "4000 kg",
      Dimensions: "35x35x35 cm",
      Description: "Chemicals",
      "Cargo Type": "Hazardous",
      "Special Handling Instructions": "Handle with care",
      "Packaging Type": "Pallet",
      "Cargo Value": "$6000",
      "Temperature Requirements": "20°C - 25°C",
      "Fragile Indicator": "Yes",
      "Cargo Insurance": "Policy #12351",
      "Cargo Temperature Requirements": "20°C - 25°C",
      "Cargo Labeling Requirements": "Hazardous",
      "Cargo Packaging Requirements": "Sealed Box",
    },
    {
      Weight: "4500 kg",
      Dimensions: "40x40x40 cm",
      Description: "Artwork",
      "Cargo Type": "Fine Art",
      "Special Handling Instructions": "Fragile",
      "Packaging Type": "Box",
      "Cargo Value": "$7000",
      "Temperature Requirements": "Room Temperature",
      "Fragile Indicator": "Yes",
      "Cargo Insurance": "Policy #12352",
      "Cargo Temperature Requirements": "N/A",
      "Cargo Labeling Requirements": "Fragile",
      "Cargo Packaging Requirements": "Wooden Crate",
    },
    {
      Weight: "5000 kg",
      Dimensions: "45x45x45 cm",
      Description: "Automotive Parts",
      "Cargo Type": "Automotive",
      "Special Handling Instructions": "None",
      "Packaging Type": "Crate",
      "Cargo Value": "$8000",
      "Temperature Requirements": "N/A",
      "Fragile Indicator": "No",
      "Cargo Insurance": "Policy #12353",
      "Cargo Temperature Requirements": "N/A",
      "Cargo Labeling Requirements": "Heavy",
      "Cargo Packaging Requirements": "Metal Crate",
    },
  ],
  Customer_Information: [
    {
      "First Name": "John",
      "Last Name": "Doe",
      "Email Address": "john.doe@example.com",
      "Contact Number": "+1 123 456 7890",
      "Country of Residence": "USA",
      "Middle Name": "A",
      "Alternate Contact Number": "+1 098 765 4321",
      "Company Name": "ABC Corp",
      Address: "123 Main St",
      "Zip/Postal Code": "12345",
      Company: "ABC Corp, Dept 101",
      "Customer Tax Identification": "12-3456789",
    },
    {
      "First Name": "Emily",
      "Last Name": "Smith",
      "Email Address": "emily.smith@example.com",
      "Contact Number": "+1 987 654 3210",
      "Country of Residence": "Canada",
      "Middle Name": "B",
      "Alternate Contact Number": "+1 321 654 9870",
      "Company Name": "XYZ Ltd",
      Address: "456 Elm St",
      "Zip/Postal Code": "67890",
      Company: "XYZ Ltd, Dept 202",
      "Customer Tax Identification": "98-7654321",
    },
    {
      "First Name": "Alice",
      "Last Name": "Johnson",
      "Email Address": "alice.j@example.com",
      "Contact Number": "+44 20 7946 0958",
      "Country of Residence": "UK",
      "Middle Name": "",
      "Alternate Contact Number": "",
      "Company Name": "",
      Address: "789 Oak St",
      "Zip/Postal Code": "W1A 1AA",
      Company: "",
      "Customer Tax Identification": "",
    },
    {
      "First Name": "Michael",
      "Last Name": "Brown",
      "Email Address": "mike.b@example.com",
      "Contact Number": "+61 2 9374 4001",
      "Country of Residence": "Australia",
      "Middle Name": "C",
      "Alternate Contact Number": "+61 2 9374 4002",
      "Company Name": "DEF Pty",
      Address: "101 Pine St",
      "Zip/Postal Code": "2000",
      Company: "DEF Pty, Dept 303",
      "Customer Tax Identification": "56-7890123",
    },
    {
      "First Name": "Sarah",
      "Last Name": "Williams",
      "Email Address": "sarah.w@example.com",
      "Contact Number": "+81 3 1234 5678",
      "Country of Residence": "Japan",
      "Middle Name": "",
      "Alternate Contact Number": "",
      "Company Name": "",
      Address: "202 Maple St",
      "Zip/Postal Code": "100-0001",
      Company: "",
      "Customer Tax Identification": "",
    },
    {
      "First Name": "David",
      "Last Name": "Lee",
      "Email Address": "david.lee@example.com",
      "Contact Number": "+1 555 444 3333",
      "Country of Residence": "USA",
      "Middle Name": "D",
      "Alternate Contact Number": "+1 555 444 3334",
      "Company Name": "GHI Inc",
      Address: "303 Cedar St",
      "Zip/Postal Code": "30303",
      Company: "GHI Inc, Dept 404",
      "Customer Tax Identification": "34-5678901",
    },
    {
      "First Name": "Karen",
      "Last Name": "White",
      "Email Address": "karen.white@example.com",
      "Contact Number": "+44 20 7946 1111",
      "Country of Residence": "UK",
      "Middle Name": "E",
      "Alternate Contact Number": "+44 20 7946 2222",
      "Company Name": "JKL Ltd",
      Address: "404 Birch St",
      "Zip/Postal Code": "EC1A 1BB",
      Company: "JKL Ltd, Dept 505",
      "Customer Tax Identification": "78-9012345",
    },
    {
      "First Name": "Paul",
      "Last Name": "Garcia",
      "Email Address": "paul.g@example.com",
      "Contact Number": "+61 2 9374 5555",
      "Country of Residence": "Australia",
      "Middle Name": "",
      "Alternate Contact Number": "",
      "Company Name": "+61 2 9374 6666",
      Address: "MNO Pty",
      "Zip/Postal Code": "505 Spruce St",
      Company: "3000",
      "Customer Tax Identification": "MNO Pty, Dept 606",
    },
    {
      "First Name": "Grace",
      "Last Name": "Martinez",
      "Email Address": "grace.m@example.com",
      "Contact Number": "+81 3 1234 8888",
      "Country of Residence": "Japan",
      "Middle Name": "F",
      "Alternate Contact Number": "+81 3 1234 9999",
      "Company Name": "PQR Corp",
      Address: "606 Pine St",
      "Zip/Postal Code": "200-0002",
      Company: "PQR Corp, Dept 707",
      "Customer Tax Identification": "98-7654321",
    },
  ],
  Feedback: [
    {
      "Overall Experience Rating": "4 stars",
      "Comments or Suggestions": "Great service!",
      "Would you recommend us?": "Yes",
      "What can we improve?": "Faster delivery",
      "Any specific issues encountered": "Late delivery",
    },
    {
      "Overall Experience Rating": "5 stars",
      "Comments or Suggestions": "Excellent experience!",
      "Would you recommend us?": "Yes",
      "What can we improve?": "N/A",
      "Any specific issues encountered": "N/A",
    },
    {
      "Overall Experience Rating": "3 stars",
      "Comments or Suggestions": "Average service",
      "Would you recommend us?": "No",
      "What can we improve?": "Customer support",
      "Any specific issues encountered": "Wrong item delivered",
    },
    {
      "Overall Experience Rating": "2 stars",
      "Comments or Suggestions": "Poor experience",
      "Would you recommend us?": "No",
      "What can we improve?": "Delivery time",
      "Any specific issues encountered": "Late delivery",
    },
    {
      "Overall Experience Rating": "4 stars",
      "Comments or Suggestions": "Good but can improve",
      "Would you recommend us?": "Yes",
      "What can we improve?": "Product quality",
      "Any specific issues encountered": "Damaged item",
    },
    {
      "Overall Experience Rating": "1 star",
      "Comments or Suggestions": "Terrible service",
      "Would you recommend us?": "No",
      "What can we improve?": "Everything",
      "Any specific issues encountered": "Wrong item delivered",
    },
    {
      "Overall Experience Rating": "5 stars",
      "Comments or Suggestions": "Beyond expectations",
      "Would you recommend us?": "Yes",
      "What can we improve?": "N/A",
      "Any specific issues encountered": "N/A",
    },
    {
      "Overall Experience Rating": "3 stars",
      "Comments or Suggestions": "Satisfactory",
      "Would you recommend us?": "Maybe",
      "What can we improve?": "Pricing",
      "Any specific issues encountered": "High shipping cost",
    },
    {
      "Overall Experience Rating": "4 stars",
      "Comments or Suggestions": "Very good",
      "Would you recommend us?": "Yes",
      "What can we improve?": "Packaging",
      "Any specific issues encountered": "Damaged packaging",
    },
  ],
  Loyalty_Program: [
    {
      "Membership ID (if applicable)": "12345",
      "Points per dollar spent": "5",
      Rewards: "$10 Gift Card",
      "Terms and conditions": true,
      "Membership ID or Number": "67890",
      "Membership Tier": "Gold",
      Description: "Frequent flyer",
      "Points Redeem Option": "Gift Card",
      "Special Requests for Members": "Priority Handling",
      "Referral Code": "REF2023",
    },
    {
      "Membership ID (if applicable)": "23456",
      "Points per dollar spent": "4",
      Rewards: "$20 Gift Card",
      "Terms and conditions": true,
      "Membership ID or Number": "78901",
      "Membership Tier": "Silver",
      Description: "Business Class",
      "Points Redeem Option": "Air Miles",
      "Special Requests for Members": "Early Boarding",
      "Referral Code": "REF2024",
    },
    {
      "Membership ID (if applicable)": "34567",
      "Points per dollar spent": "3",
      Rewards: "Free Meal",
      "Terms and conditions": true,
      "Membership ID or Number": "89012",
      "Membership Tier": "Platinum",
      Description: "Premium Member",
      "Points Redeem Option": "Discount Coupon",
      "Special Requests for Members": "Lounge Access",
      "Referral Code": "REF2025",
    },
    {
      "Membership ID (if applicable)": "45678",
      "Points per dollar spent": "5",
      Rewards: "$10 Gift Card",
      "Terms and conditions": true,
      "Membership ID or Number": "90123",
      "Membership Tier": "Gold",
      Description: "Frequent flyer",
      "Points Redeem Option": "Gift Card",
      "Special Requests for Members": "Priority Handling",
      "Referral Code": "REF2026",
    },
    {
      "Membership ID (if applicable)": "56789",
      "Points per dollar spent": "4",
      Rewards: "$20 Gift Card",
      "Terms and conditions": true,
      "Membership ID or Number": "01234",
      "Membership Tier": "Silver",
      Description: "Business Class",
      "Points Redeem Option": "Air Miles",
      "Special Requests for Members": "Early Boarding",
      "Referral Code": "REF2027",
    },
    {
      "Membership ID (if applicable)": "67890",
      "Points per dollar spent": "3",
      Rewards: "Free Meal",
      "Terms and conditions": true,
      "Membership ID or Number": "12345",
      "Membership Tier": "Platinum",
      Description: "Premium Member",
      "Points Redeem Option": "Discount Coupon",
      "Special Requests for Members": "Lounge Access",
      "Referral Code": "REF2028",
    },
    {
      "Membership ID (if applicable)": "78901",
      "Points per dollar spent": "5",
      Rewards: "$10 Gift Card",
      "Terms and conditions": true,
      "Membership ID or Number": "23456",
      "Membership Tier": "Gold",
      Description: "Frequent flyer",
      "Points Redeem Option": "Gift Card",
      "Special Requests for Members": "Priority Handling",
      "Referral Code": "REF2029",
    },
    {
      "Membership ID (if applicable)": "89012",
      "Points per dollar spent": "4",
      Rewards: "$20 Gift Card",
      "Terms and conditions": true,
      "Membership ID or Number": "34567",
      "Membership Tier": "Silver",
      Description: "Business Class",
      "Points Redeem Option": "Air Miles",
      "Special Requests for Members": "Early Boarding",
      "Referral Code": "REF2030",
    },
    {
      "Membership ID (if applicable)": "90123",
      "Points per dollar spent": "3",
      Rewards: "Free Meal",
      "Terms and conditions": true,
      "Membership ID or Number": "45678",
      "Membership Tier": "Platinum",
      Description: "Premium Member",
      "Points Redeem Option": "Discount Coupon",
      "Special Requests for Members": "Lounge Access",
      "Referral Code": "REF2031",
    },
  ],
  Payment_Information: [
    {
      "Payment Method": "Credit Card",
      "Cardholder Name": "John Doe",
      "Card Number": "4111111111111111",
      "Expiry Date": "12/2023",
      "CVV/CVC Code": "123",
      "Billing Name": "John Doe",
      "Billing Address": "123 Main St",
      "Billing Phone Number": "+1 123-456-7890",
      "Billing Email Address": "john.doe@example.com",
      "Save Payment Information for Future Use": "Yes",
      "Promo Code": "PROMO2023",
      "Additional Payment Notes": "Pay before 15th",
      "Alternate Payment Method": "PayPal",
    },
    {
      "Payment Method": "Debit Card",
      "Cardholder Name": "Emily Smith",
      "Card Number": "5111111111111111",
      "Expiry Date": "11/2022",
      "CVV/CVC Code": "234",
      "Billing Name": "Emily Smith",
      "Billing Address": "456 Elm St",
      "Billing Phone Number": "+1 987-654-3210",
      "Billing Email Address": "emily.smith@example.com",
      "Save Payment Information for Future Use": "No",
      "Promo Code": "PROMO2024",
      "Additional Payment Notes": "Pay on delivery",
      "Alternate Payment Method": "",
    },
    {
      "Payment Method": "PayPal",
      "Cardholder Name": "Alice Johnson",
      "Card Number": "",
      "Expiry Date": "",
      "CVV/CVC Code": "",
      "Billing Name": "Alice Johnson",
      "Billing Address": "789 Oak St",
      "Billing Phone Number": "+44 20 7946 0958",
      "Billing Email Address": "alice.j@example.com",
      "Save Payment Information for Future Use": "Yes",
      "Promo Code": "",
      "Additional Payment Notes": "",
      "Alternate Payment Method": "",
    },
    {
      "Payment Method": "Credit Card",
      "Cardholder Name": "Michael Brown",
      "Card Number": "6111111111111111",
      "Expiry Date": "10/2024",
      "CVV/CVC Code": "345",
      "Billing Name": "Michael Brown",
      "Billing Address": "101 Pine St",
      "Billing Phone Number": "+61 2 9374 4001",
      "Billing Email Address": "mike.b@example.com",
      "Save Payment Information for Future Use": "No",
      "Promo Code": "PROMO2025",
      "Additional Payment Notes": "Pay in 30 days",
      "Alternate Payment Method": "Debit Card",
    },
    {
      "Payment Method": "Debit Card",
      "Cardholder Name": "Sarah Williams",
      "Card Number": "7111111111111111",
      "Expiry Date": "09/2025",
      "CVV/CVC Code": "456",
      "Billing Name": "Sarah Williams",
      "Billing Address": "202 Maple St",
      "Billing Phone Number": "+81 3 1234 5678",
      "Billing Email Address": "sarah.w@example.com",
      "Save Payment Information for Future Use": "Yes",
      "Promo Code": "",
      "Additional Payment Notes": "",
      "Alternate Payment Method": "Credit Card",
    },
    {
      "Payment Method": "Credit Card",
      "Cardholder Name": "David Lee",
      "Card Number": "8111111111111111",
      "Expiry Date": "08/2026",
      "CVV/CVC Code": "567",
      "Billing Name": "David Lee",
      "Billing Address": "303 Cedar St",
      "Billing Phone Number": "+1 555-444-3333",
      "Billing Email Address": "david.lee@example.com",
      "Save Payment Information for Future Use": "No",
      "Promo Code": "PROMO2026",
      "Additional Payment Notes": "Pay in 7 days",
      "Alternate Payment Method": "PayPal",
    },
    {
      "Payment Method": "PayPal",
      "Cardholder Name": "Karen White",
      "Card Number": "",
      "Expiry Date": "",
      "CVV/CVC Code": "",
      "Billing Name": "Karen White",
      "Billing Address": "404 Birch St",
      "Billing Phone Number": "+44 20 7946 1111",
      "Billing Email Address": "karen.white@example.com",
      "Save Payment Information for Future Use": "Yes",
      "Promo Code": "",
      "Additional Payment Notes": "",
      "Alternate Payment Method": "",
    },
    {
      "Payment Method": "Credit Card",
      "Cardholder Name": "Paul Garcia",
      "Card Number": "9111111111111111",
      "Expiry Date": "07/2027",
      "CVV/CVC Code": "678",
      "Billing Name": "Paul Garcia",
      "Billing Address": "505 Spruce St",
      "Billing Phone Number": "+61 2 9374 5555",
      "Billing Email Address": "paul.g@example.com",
      "Save Payment Information for Future Use": "No",
      "Promo Code": "PROMO2027",
      "Additional Payment Notes": "Pay on receipt",
      "Alternate Payment Method": "Debit Card",
    },
    {
      "Payment Method": "Debit Card",
      "Cardholder Name": "Grace Martinez",
      "Card Number": "0111111111111111",
      "Expiry Date": "06/2028",
      "CVV/CVC Code": "789",
      "Billing Name": "Grace Martinez",
      "Billing Address": "606 Pine St",
      "Billing Phone Number": "+81 3 1234 8888",
      "Billing Email Address": "grace.m@example.com",
      "Save Payment Information for Future Use": "Yes",
      "Promo Code": "",
      "Additional Payment Notes": "",
      "Alternate Payment Method": "Credit Card",
    },
  ],
  Promotions_and_Discounts: [
    {
      "Coupon Code": "COUPON2023",
      "Promotion Name": "Summer Sale",
      "Discount Percentage": "20",
      "Start Date": "2023-06-01",
      "End Date": "2023-06-30",
      "Eligibility Criteria": "New Customers",
      "Promo Code or Coupon Code": "PROMO2023",
      "Loyalty Points Redemption": "1000",
      "Gift Card Number": "GIFT1234",
      "Referral Code": "REF2023",
      "Special Offer Selection": "Early Bird Discount",
      Description: "Limited Time Offer",
    },
    {
      "Coupon Code": "COUPON2024",
      "Promotion Name": "Winter Sale",
      "Discount Percentage": "25",
      "Start Date": "2023-12-01",
      "End Date": "2023-12-31",
      "Eligibility Criteria": "Existing Customers",
      "Promo Code or Coupon Code": "PROMO2024",
      "Loyalty Points Redemption": "2000",
      "Gift Card Number": "GIFT1235",
      "Referral Code": "REF2024",
      "Special Offer Selection": "Seasonal Offer",
      Description: "Holiday Special",
    },
    {
      "Coupon Code": "COUPON2025",
      "Promotion Name": "Spring Sale",
      "Discount Percentage": "15",
      "Start Date": "2023-03-01",
      "End Date": "2023-03-31",
      "Eligibility Criteria": "All Customers",
      "Promo Code or Coupon Code": "PROMO2025",
      "Loyalty Points Redemption": "500",
      "Gift Card Number": "GIFT1236",
      "Referral Code": "REF2025",
      "Special Offer Selection": "Early Bird Discount",
      Description: "Spring Fling",
    },
    {
      "Coupon Code": "COUPON2026",
      "Promotion Name": "Autumn Sale",
      "Discount Percentage": "30",
      "Start Date": "2023-09-01",
      "End Date": "2023-09-30",
      "Eligibility Criteria": "First Purchase",
      "Promo Code or Coupon Code": "PROMO2026",
      "Loyalty Points Redemption": "1500",
      "Gift Card Number": "GIFT1237",
      "Referral Code": "REF2026",
      "Special Offer Selection": "Seasonal Offer",
      Description: "Fall Festival",
    },
    {
      "Coupon Code": "COUPON2027",
      "Promotion Name": "Back to School",
      "Discount Percentage": "10",
      "Start Date": "2023-08-01",
      "End Date": "2023-08-31",
      "Eligibility Criteria": "Students",
      "Promo Code or Coupon Code": "PROMO2027",
      "Loyalty Points Redemption": "300",
      "Gift Card Number": "GIFT1238",
      "Referral Code": "REF2027",
      "Special Offer Selection": "Early Bird Discount",
      Description: "Educational Discount",
    },
    {
      "Coupon Code": "COUPON2028",
      "Promotion Name": "Black Friday",
      "Discount Percentage": "50",
      "Start Date": "2023-11-24",
      "End Date": "2023-11-24",
      "Eligibility Criteria": "All Customers",
      "Promo Code or Coupon Code": "PROMO2028",
      "Loyalty Points Redemption": "5000",
      "Gift Card Number": "GIFT1239",
      "Referral Code": "REF2028",
      "Special Offer Selection": "Seasonal Offer",
      Description: "One Day Only",
    },
    {
      "Coupon Code": "COUPON2029",
      "Promotion Name": "Cyber Monday",
      "Discount Percentage": "40",
      "Start Date": "2023-11-27",
      "End Date": "2023-11-27",
      "Eligibility Criteria": "Online Purchases",
      "Promo Code or Coupon Code": "PROMO2029",
      "Loyalty Points Redemption": "4000",
      "Gift Card Number": "GIFT1240",
      "Referral Code": "REF2029",
      "Special Offer Selection": "Early Bird Discount",
      Description: "Online Exclusive",
    },
    {
      "Coupon Code": "COUPON2030",
      "Promotion Name": "Valentine's Day",
      "Discount Percentage": "14",
      "Start Date": "2023-02-14",
      "End Date": "2023-02-14",
      "Eligibility Criteria": "Couples",
      "Promo Code or Coupon Code": "PROMO2030",
      "Loyalty Points Redemption": "700",
      "Gift Card Number": "GIFT1241",
      "Referral Code": "REF2030",
      "Special Offer Selection": "Seasonal Offer",
      Description: "Love is in the Air",
    },
    {
      "Coupon Code": "COUPON2031",
      "Promotion Name": "Easter Sale",
      "Discount Percentage": "20",
      "Start Date": "2023-04-16",
      "End Date": "2023-04-16",
      "Eligibility Criteria": "All Customers",
      "Promo Code or Coupon Code": "PROMO2031",
      "Loyalty Points Redemption": "800",
      "Gift Card Number": "GIFT1242",
      "Referral Code": "REF2031",
      "Special Offer Selection": "Early Bird Discount",
      Description: "Egg-citing Offers",
    },
  ],
  Shipment_Details: [
    {
      Origin: "New York",
      Destination: "Los Angeles",
      "Shipment Type": "Air",
      "Shipment Date": "2023-09-15",
      "Estimated Arrival Date": "2023-09-20",
      "Freight Type": "Container",
      Weight: "2000",
      Dimensions: "10x10x10",
      "Hazardous Materials": "Yes",
      "Special Handling Requirements": "Handle with care",
      "Transit Stops": "Chicago",
      "Cargo Tracking Number": "CTN123456",
      "Airway Bill Number": "AWB789012",
      "Carrier Preference": "FedEx",
    },
    {
      Origin: "Chicago",
      Destination: "San Francisco",
      "Shipment Type": "Sea",
      "Shipment Date": "2023-09-16",
      "Estimated Arrival Date": "2023-09-25",
      "Freight Type": "Bulk",
      Weight: "1500",
      Dimensions: "15x15x15",
      "Hazardous Materials": "No",
      "Special Handling Requirements": "Fragile",
      "Transit Stops": "Denver",
      "Cargo Tracking Number": "CTN123457",
      "Airway Bill Number": "AWB789013",
      "Carrier Preference": "UPS",
    },
    {
      Origin: "San Francisco",
      Destination: "Seattle",
      "Shipment Type": "Land",
      "Shipment Date": "2023-09-17",
      "Estimated Arrival Date": "2023-09-18",
      "Freight Type": "Container",
      Weight: "1000",
      Dimensions: "5x5x5",
      "Hazardous Materials": "Yes",
      "Special Handling Requirements": "None",
      "Transit Stops": "Portland",
      "Cargo Tracking Number": "CTN123458",
      "Airway Bill Number": "AWB789014",
      "Carrier Preference": "DHL",
    },
    {
      Origin: "Seattle",
      Destination: "New York",
      "Shipment Type": "Air",
      "Shipment Date": "2023-09-18",
      "Estimated Arrival Date": "2023-09-19",
      "Freight Type": "Bulk",
      Weight: "2500",
      Dimensions: "20x20x20",
      "Hazardous Materials": "No",
      "Special Handling Requirements": "Handle with care",
      "Transit Stops": "Chicago",
      "Cargo Tracking Number": "CTN123459",
      "Airway Bill Number": "AWB789015",
      "Carrier Preference": "FedEx",
    },
    {
      Origin: "Los Angeles",
      Destination: "Chicago",
      "Shipment Type": "Sea",
      "Shipment Date": "2023-09-19",
      "Estimated Arrival Date": "2023-09-29",
      "Freight Type": "Container",
      Weight: "3000",
      Dimensions: "25x25x25",
      "Hazardous Materials": "Yes",
      "Special Handling Requirements": "Fragile",
      "Transit Stops": "San Francisco",
      "Cargo Tracking Number": "CTN123460",
      "Airway Bill Number": "AWB789016",
      "Carrier Preference": "UPS",
    },
    {
      Origin: "Chicago",
      Destination: "San Francisco",
      "Shipment Type": "Land",
      "Shipment Date": "2023-09-20",
      "Estimated Arrival Date": "2023-09-21",
      "Freight Type": "Bulk",
      Weight: "3500",
      Dimensions: "30x30x30",
      "Hazardous Materials": "No",
      "Special Handling Requirements": "None",
      "Transit Stops": "Denver",
      "Cargo Tracking Number": "CTN123461",
      "Airway Bill Number": "AWB789017",
      "Carrier Preference": "DHL",
    },
    {
      Origin: "San Francisco",
      Destination: "Seattle",
      "Shipment Type": "Air",
      "Shipment Date": "2023-09-21",
      "Estimated Arrival Date": "2023-09-22",
      "Freight Type": "Container",
      Weight: "4000",
      Dimensions: "35x35x35",
      "Hazardous Materials": "Yes",
      "Special Handling Requirements": "Handle with care",
      "Transit Stops": "Portland",
      "Cargo Tracking Number": "CTN123462",
      "Airway Bill Number": "AWB789018",
      "Carrier Preference": "FedEx",
    },
    {
      Origin: "Seattle",
      Destination: "New York",
      "Shipment Type": "Sea",
      "Shipment Date": "2023-09-22",
      "Estimated Arrival Date": "2023-10-02",
      "Freight Type": "Bulk",
      Weight: "4500",
      Dimensions: "40x40x40",
      "Hazardous Materials": "No",
      "Special Handling Requirements": "Fragile",
      "Transit Stops": "Chicago",
      "Cargo Tracking Number": "CTN123463",
      "Airway Bill Number": "AWB789019",
      "Carrier Preference": "UPS",
    },
    {
      Origin: "Los Angeles",
      Destination: "Chicago",
      "Shipment Type": "Land",
      "Shipment Date": "2023-09-23",
      "Estimated Arrival Date": "2023-09-24",
      "Freight Type": "Container",
      Weight: "5000",
      Dimensions: "45x45x45",
      "Hazardous Materials": "Yes",
      "Special Handling Requirements": "None",
      "Transit Stops": "San Francisco",
      "Cargo Tracking Number": "CTN123464",
      "Airway Bill Number": "AWB789020",
      "Carrier Preference": "DHL",
    },
  ],
  Terms_and_Conditions: [
    {
      "Terms and Conditions": true,
      Document: "https://example.com/terms",
      "Privacy Policy": true,
      "Cancellation Policy": true,
      "Additional Agreements": true,
      "Digital Signature Field": "Signature1.png",
    },
    {
      "Terms and Conditions": true,
      Document: "https://example.com/terms",
      "Privacy Policy": false,
      "Cancellation Policy": true,
      "Additional Agreements": false,
      "Digital Signature Field": "Signature2.png",
    },
    {
      "Terms and Conditions": true,
      Document: "https://example.com/terms",
      "Privacy Policy": true,
      "Cancellation Policy": false,
      "Additional Agreements": true,
      "Digital Signature Field": "Signature3.png",
    },
    {
      "Terms and Conditions": true,
      Document: "https://example.com/terms",
      "Privacy Policy": false,
      "Cancellation Policy": false,
      "Additional Agreements": false,
      "Digital Signature Field": "Signature4.png",
    },
    {
      "Terms and Conditions": true,
      Document: "https://example.com/terms",
      "Privacy Policy": true,
      "Cancellation Policy": true,
      "Additional Agreements": false,
      "Digital Signature Field": "Signature5.png",
    },
    {
      "Terms and Conditions": true,
      Document: "https://example.com/terms",
      "Privacy Policy": false,
      "Cancellation Policy": true,
      "Additional Agreements": true,
      "Digital Signature Field": "Signature6.png",
    },
    {
      "Terms and Conditions": true,
      Document: "https://example.com/terms",
      "Privacy Policy": true,
      "Cancellation Policy": false,
      "Additional Agreements": false,
      "Digital Signature Field": "Signature7.png",
    },
    {
      "Terms and Conditions": true,
      Document: "https://example.com/terms",
      "Privacy Policy": false,
      "Cancellation Policy": false,
      "Additional Agreements": true,
      "Digital Signature Field": "Signature8.png",
    },
    {
      "Terms and Conditions": true,
      Document: "https://example.com/terms",
      "Privacy Policy": true,
      "Cancellation Policy": true,
      "Additional Agreements": true,
      "Digital Signature Field": "Signature9.png",
    },
  ],
  Special_Instructions: [
    {
      "Specific Handling or Delivery Instructions": "Handle with care",
      "Freight Insurance": true,
      COD: false,
      "Dedicated Pickup": true,
      "Dedicated Delivery": false,
      Warehousing: true,
      "Customs Clearance": true,
    },
    {
      "Specific Handling or Delivery Instructions": "Fragile",
      "Freight Insurance": " do not drop",
      COD: false,
      "Dedicated Pickup": true,
      "Dedicated Delivery": false,
      Warehousing: true,
      "Customs Clearance": false,
    },
    {
      "Specific Handling or Delivery Instructions": "Temperature-sensitive",
      "Freight Insurance": true,
      COD: false,
      "Dedicated Pickup": true,
      "Dedicated Delivery": false,
      Warehousing: true,
      "Customs Clearance": false,
    },
    {
      "Specific Handling or Delivery Instructions": "Do not stack",
      "Freight Insurance": false,
      COD: true,
      "Dedicated Pickup": false,
      "Dedicated Delivery": true,
      Warehousing: false,
      "Customs Clearance": true,
    },
    {
      "Specific Handling or Delivery Instructions": "Keep away from sunlight",
      "Freight Insurance": true,
      COD: false,
      "Dedicated Pickup": true,
      "Dedicated Delivery": false,
      Warehousing: true,
      "Customs Clearance": false,
    },
    {
      "Specific Handling or Delivery Instructions": "Deliver after 5 PM",
      "Freight Insurance": false,
      COD: true,
      "Dedicated Pickup": false,
      "Dedicated Delivery": true,
      Warehousing: false,
      "Customs Clearance": true,
    },
    {
      "Specific Handling or Delivery Instructions":
        "Requires signature upon delivery",
      "Freight Insurance": true,
      COD: false,
      "Dedicated Pickup": true,
      "Dedicated Delivery": false,
      Warehousing: true,
      "Customs Clearance": false,
    },
    {
      "Specific Handling or Delivery Instructions": "COD only",
      "Freight Insurance": false,
      COD: true,
      "Dedicated Pickup": false,
      "Dedicated Delivery": true,
      Warehousing: false,
      "Customs Clearance": true,
    },
    {
      "Specific Handling or Delivery Instructions": "Expedite delivery",
      "Freight Insurance": true,
      COD: false,
      "Dedicated Pickup": true,
      "Dedicated Delivery": false,
      Warehousing: true,
      "Customs Clearance": false,
    },
  ],
  model: [
    {
      Section: "Customer Information",
      "Field Name": "First Name",
      "Field Description": "first name",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Text",
      "Sample Value": "John",
      "Size of Field": "50 characters",
      "Related Documents": "ID Proof",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Customer Information",
      "Field Name": "Middle Name",
      "Field Description": "middle name",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "A",
      "Size of Field": "50 characters",
      "Related Documents": "ID Proof (if present)",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Customer Information",
      "Field Name": "Last Name",
      "Field Description": "last name",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Text",
      "Sample Value": "Doe",
      "Size of Field": "50 characters",
      "Related Documents": "ID Proof",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Customer Information",
      "Field Name": "Email Address",
      "Field Description": "email address",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Email",
      "Sample Value": "john.doe@example.com",
      "Size of Field": "100 characters",
      "Related Documents": "Email Verification",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Customer Information",
      "Field Name": "Contact Number",
      "Field Description": "Land Line and Mobile",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Number",
      "Sample Value": "+1 123 456 7890",
      "Size of Field": "15 digits",
      "Related Documents": "Phone Bill",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Customer Information",
      "Field Name": "Country of Residence",
      "Field Description": "country of residence",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Dropdown",
      "Sample Value": "USA",
      "Size of Field": "N/A",
      "Related Documents": "Passport",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Customer Information",
      "Field Name": "Alternate Contact Number",
      "Field Description": "Alternate Land Line and Mobile",
      "Mandatory / Optional": "Optional",
      "Data Type": "Number",
      "Sample Value": "+1 098 765 4321",
      "Size of Field": "15 digits",
      "Related Documents": "Phone Bill (if present)",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Customer Information",
      "Field Name": "Company Name",
      "Field Description": "Name of the company",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "ABC Corp",
      "Size of Field": "100 characters",
      "Related Documents": "Business License",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Customer Information",
      "Field Name": "Address",
      "Field Description": "address",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "123 Main St",
      "Size of Field": "200 characters",
      "Related Documents": "Utility Bill",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Customer Information",
      "Field Name": "Zip/Postal Code",
      "Field Description": "zip or postal code",
      "Mandatory / Optional": "Optional",
      "Data Type": "Number",
      "Sample Value": "12345",
      "Size of Field": "10 digits",
      "Related Documents": "Utility Bill",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Customer Information",
      "Field Name": "Company (if applicable)",
      "Field Description": "Company details if customer represents one",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "ABC Corp, Dept 101",
      "Size of Field": "100 characters",
      "Related Documents": "Business License",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Customer Information",
      "Field Name": "Customer Tax Identification",
      "Field Description": "tax ID",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "12-3456789",
      "Size of Field": "20 characters",
      "Related Documents": "Tax Documents",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Shipment Details",
      "Field Name": "Origin",
      "Field Description": "Starting location of the shipment",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Dropdown",
      "Sample Value": "New York",
      "Size of Field": "N/A",
      "Related Documents": "Shipping Manifest",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Shipment Details",
      "Field Name": "Destination",
      "Field Description": "Final location of the shipment",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Dropdown",
      "Sample Value": "Los Angeles",
      "Size of Field": "N/A",
      "Related Documents": "Shipping Manifest",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Shipment Details",
      "Field Name": "Shipment Type",
      "Field Description": "Type of shipment (e.g., air, sea, land)",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Radio Group",
      "Sample Value": "Air",
      "Size of Field": "N/A",
      "Related Documents": "Shipping Manifest",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Shipment Details",
      "Field Name": "Shipment Date",
      "Field Description": "Date of shipment",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Date",
      "Sample Value": "2023-09-15",
      "Size of Field": "N/A",
      "Related Documents": "Shipping Manifest",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Shipment Details",
      "Field Name": "Estimated Arrival Date",
      "Field Description": "Estimated date of arrival",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Date",
      "Sample Value": "2023-09-20",
      "Size of Field": "N/A",
      "Related Documents": "Shipping Manifest",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Shipment Details",
      "Field Name": "Freight Type",
      "Field Description": "Type of freight (e.g., bulk, container)",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Dropdown",
      "Sample Value": "Container",
      "Size of Field": "N/A",
      "Related Documents": "Shipping Manifest",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Shipment Details",
      "Field Name": "Weight",
      "Field Description": "Weight of the shipment",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Number",
      "Sample Value": "2000",
      "Size of Field": "10 digits",
      "Related Documents": "Weight Certificate",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Shipment Details",
      "Field Name": "Dimensions",
      "Field Description": "Dimensions of the shipment",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "10x10x10",
      "Size of Field": "20 characters",
      "Related Documents": "Shipping Manifest",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Shipment Details",
      "Field Name": "Hazardous Materials",
      "Field Description": "Any hazardous materials in the shipment",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": "Yes",
      "Size of Field": "N/A",
      "Related Documents": "Hazardous Material Certificate",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Shipment Details",
      "Field Name": "Special Handling Requirements",
      "Field Description": "Special requirements for handling",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "Handle with care",
      "Size of Field": "100 characters",
      "Related Documents": "Special Handling Certificate",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Shipment Details",
      "Field Name": "Transit Stops",
      "Field Description": "Stops during transit",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "Chicago",
      "Size of Field": "100 characters",
      "Related Documents": "Shipping Manifest",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Shipment Details",
      "Field Name": "Cargo Tracking Number",
      "Field Description": "Tracking number for the cargo",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "CTN123456",
      "Size of Field": "20 characters",
      "Related Documents": "Tracking Information",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Shipment Details",
      "Field Name": "Airway Bill Number",
      "Field Description": "Airway bill number for the shipment",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "AWB789012",
      "Size of Field": "20 characters",
      "Related Documents": "Airway Bill",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Shipment Details",
      "Field Name": "Carrier Preference",
      "Field Description": "Preferred carrier for the shipment",
      "Mandatory / Optional": "Optional",
      "Data Type": "Dropdown",
      "Sample Value": "FedEx",
      "Size of Field": "N/A",
      "Related Documents": "Carrier Agreement",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Cargo Information",
      "Field Name": "Weight",
      "Field Description": "Weight of the cargo",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Number",
      "Sample Value": "2000 kg",
      "Size of Field": "10 digits",
      "Related Documents": "Weight Certificate",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Cargo Information",
      "Field Name": "Dimensions",
      "Field Description": "Dimensions of the cargo (LxWxH)",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Text",
      "Sample Value": "10x10x10 cm",
      "Size of Field": "20 characters",
      "Related Documents": "Dimension Certificate",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Cargo Information",
      "Field Name": "Description",
      "Field Description": "Description of the cargo",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Text",
      "Sample Value": "Electronics",
      "Size of Field": "100 characters",
      "Related Documents": "Cargo Manifest",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Cargo Information",
      "Field Name": "Cargo Type",
      "Field Description": "Type of cargo (e.g., perishable, electronics)",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Dropdown",
      "Sample Value": "Electronics",
      "Size of Field": "N/A",
      "Related Documents": "Cargo Manifest",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Cargo Information",
      "Field Name": "Special Handling Instructions",
      "Field Description": "Special instructions for handling",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "Handle with care",
      "Size of Field": "100 characters",
      "Related Documents": "Special Handling Certificate",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Cargo Information",
      "Field Name": "Packaging Type",
      "Field Description": "Type of packaging (e.g., Pallet, Box, Crate)",
      "Mandatory / Optional": "Optional",
      "Data Type": "Dropdown",
      "Sample Value": "Pallet",
      "Size of Field": "N/A",
      "Related Documents": "Packaging Certificate",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Cargo Information",
      "Field Name": "Cargo Value",
      "Field Description": "Monetary value of the cargo",
      "Mandatory / Optional": "Optional",
      "Data Type": "Number",
      "Sample Value": "$5000",
      "Size of Field": "10 digits",
      "Related Documents": "Invoice",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Cargo Information",
      "Field Name": "Temperature Requirements",
      "Field Description": "Required temperature for the cargo",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "20°C - 25°C",
      "Size of Field": "20 characters",
      "Related Documents": "Temperature Log",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Cargo Information",
      "Field Name": "Fragile Indicator",
      "Field Description": "Indicates if the cargo is fragile",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": "Yes",
      "Size of Field": "N/A",
      "Related Documents": "Fragile Certificate",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Cargo Information",
      "Field Name": "Cargo Insurance",
      "Field Description": "Insurance details for the cargo",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "Policy #12345",
      "Size of Field": "20 characters",
      "Related Documents": "Insurance Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Cargo Information",
      "Field Name": "Cargo Temperature Requirements",
      "Field Description": "Specific temperature requirements",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "15°C - 20°C",
      "Size of Field": "20 characters",
      "Related Documents": "Temperature Log",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Cargo Information",
      "Field Name": "Cargo Labeling Requirements",
      "Field Description": "Labeling requirements for the cargo",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "Fragile",
      "Size of Field": "50 characters",
      "Related Documents": "Labeling Guidelines",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Cargo Information",
      "Field Name": "Cargo Packaging Requirements",
      "Field Description": "Packaging requirements for the cargo",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "Sealed Box",
      "Size of Field": "50 characters",
      "Related Documents": "Packaging Certificate",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Payment Information",
      "Field Name": "Field Name",
      "Field Description": "Field Description",
      "Mandatory / Optional": "Mandatory / Optional",
      "Data Type": "Data Type",
      "Sample Value": "Sample Value",
      "Size of Field": "Size of Field",
      "Related Documents": "Related Documents",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Payment Information",
      "Field Name": "Payment Method",
      "Field Description": "Preferred payment method",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Dropdown",
      "Sample Value": "Credit Card",
      "Size of Field": "N/A",
      "Related Documents": "Payment Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Payment Information",
      "Field Name": "Cardholder Name",
      "Field Description": "Name as it appears on the card",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Text",
      "Sample Value": "John Doe",
      "Size of Field": "50 characters",
      "Related Documents": "Payment Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Payment Information",
      "Field Name": "Card Number",
      "Field Description": "Card number associated with payment method",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Text",
      "Sample Value": "4111111111111111",
      "Size of Field": "16 digits",
      "Related Documents": "Payment Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Payment Information",
      "Field Name": "Expiry Date",
      "Field Description": "Expiration date of the card",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Date",
      "Sample Value": "12/2023",
      "Size of Field": "N/A",
      "Related Documents": "Payment Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Payment Information",
      "Field Name": "CVV/CVC Code",
      "Field Description": "Security code of the card",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Number",
      "Sample Value": "123",
      "Size of Field": "3-4 digits",
      "Related Documents": "Payment Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Payment Information",
      "Field Name": "Billing Name",
      "Field Description": "Name associated with the billing address",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Text",
      "Sample Value": "John Doe",
      "Size of Field": "50 characters",
      "Related Documents": "Billing Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Payment Information",
      "Field Name": "Billing Address",
      "Field Description": "Address where the card is registered",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Text",
      "Sample Value": "123 Main St",
      "Size of Field": "100 characters",
      "Related Documents": "Billing Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Payment Information",
      "Field Name": "Billing Phone Number",
      "Field Description": "Phone number associated with billing address",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "#ERROR!",
      "Size of Field": "15 characters",
      "Related Documents": "Billing Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Payment Information",
      "Field Name": "Billing Email Address",
      "Field Description": "Email address associated with billing address",
      "Mandatory / Optional": "Optional",
      "Data Type": "Email",
      "Sample Value": "john.doe@example.com",
      "Size of Field": "50 characters",
      "Related Documents": "Billing Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Payment Information",
      "Field Name": "Save Payment Information for Future Use",
      "Field Description": "Option to save payment information",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": "Yes",
      "Size of Field": "N/A",
      "Related Documents": "Privacy Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Payment Information",
      "Field Name": "Promo Code",
      "Field Description": "Promotional code, if applicable",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "PROMO2023",
      "Size of Field": "20 characters",
      "Related Documents": "Promo Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Payment Information",
      "Field Name": "Additional Payment Notes",
      "Field Description": "Additional notes or instructions",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "Pay before 15th",
      "Size of Field": "100 characters",
      "Related Documents": "Payment Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Payment Information",
      "Field Name": "Alternate Payment Method",
      "Field Description": "Alternate payment method, if any",
      "Mandatory / Optional": "Optional",
      "Data Type": "Dropdown",
      "Sample Value": "PayPal",
      "Size of Field": "N/A",
      "Related Documents": "",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Terms and Conditions",
      "Field Name": "Terms and Conditions",
      "Field Description": "Checkbox to agree to the Terms and Conditions",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Terms and Conditions Document",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Terms and Conditions",
      "Field Name": "Document",
      "Field Description": "Link to the full document of Terms and Conditions",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "URL",
      "Sample Value": "View Document",
      "Size of Field": "N/A",
      "Related Documents": "Terms and Conditions Document",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Terms and Conditions",
      "Field Name": "Privacy Policy",
      "Field Description": "Checkbox to agree to the Privacy Policy",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Privacy Policy Document",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Terms and Conditions",
      "Field Name": "Cancellation Policy",
      "Field Description": "Checkbox to agree to the Cancellation Policy",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Cancellation Policy Document",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Terms and Conditions",
      "Field Name": "Additional Agreements",
      "Field Description":
        "Checkbox to agree to additional agreements like Loyalty Program, Promotions",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Additional Agreements Document",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Terms and Conditions",
      "Field Name": "Digital Signature Field",
      "Field Description": "Field to input digital signature",
      "Mandatory / Optional": "Optional",
      "Data Type": "File Upload",
      "Sample Value": "Signature.png",
      "Size of Field": "N/A",
      "Related Documents": "Digital Signature Guidelines",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Additional Services",
      "Field Name": "Insurance",
      "Field Description": "Option to add insurance to the shipment",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Insurance Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Additional Services",
      "Field Name": "Expedited Delivery",
      "Field Description": "Option for faster delivery",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Delivery Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Additional Services",
      "Field Name": "None",
      "Field Description": "No additional services required",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "N/A",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Additional Services",
      "Field Name": "Insurance Coverage",
      "Field Description": "Type of insurance coverage",
      "Mandatory / Optional": "Optional",
      "Data Type": "Dropdown",
      "Sample Value": "Full Coverage",
      "Size of Field": "N/A",
      "Related Documents": "Insurance Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Additional Services",
      "Field Name": "Special Handling",
      "Field Description": "Special handling requirements",
      "Mandatory / Optional": "Optional",
      "Data Type": "Dropdown",
      "Sample Value": "Fragile",
      "Size of Field": "N/A",
      "Related Documents": "Handling Guidelines",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Additional Services",
      "Field Name": "Storage Options",
      "Field Description": "Storage options for the shipment",
      "Mandatory / Optional": "Optional",
      "Data Type": "Dropdown",
      "Sample Value": "Short-term",
      "Size of Field": "N/A",
      "Related Documents": "Storage Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Additional Services",
      "Field Name": "Customs Clearance Assistance",
      "Field Description": "Assistance with customs clearance",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Customs Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Additional Services",
      "Field Name": "Cargo Tracking Service",
      "Field Description": "Option to add cargo tracking",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Tracking Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Special Instructions",
      "Field Name": "Specific Handling or Delivery Instructions",
      "Field Description": "Any specific instructions for handling or delivery",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Text",
      "Sample Value": "Handle with care",
      "Size of Field": "200 characters",
      "Related Documents": "Handling Guidelines",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Special Instructions",
      "Field Name": "Freight Insurance",
      "Field Description": "Option to add freight insurance",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Insurance Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Special Instructions",
      "Field Name": "COD (Cash on Delivery)",
      "Field Description": "Option for cash on delivery",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Payment Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Special Instructions",
      "Field Name": "Dedicated Pickup",
      "Field Description": "Option for dedicated pickup service",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Pickup Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Special Instructions",
      "Field Name": "Dedicated Delivery",
      "Field Description": "Option for dedicated delivery service",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Delivery Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Special Instructions",
      "Field Name": "Warehousing",
      "Field Description": "Option for warehousing services",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Warehousing Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Special Instructions",
      "Field Name": "Customs Clearance",
      "Field Description": "Option for customs clearance assistance",
      "Mandatory / Optional": "Optional",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Customs Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Loyalty Program",
      "Field Name": "Membership ID (if applicable)",
      "Field Description": "ID for existing members",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "12345",
      "Size of Field": "10 characters",
      "Related Documents": "Membership Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Loyalty Program",
      "Field Name": "Points per dollar spent",
      "Field Description": "Points earned per dollar spent",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Number",
      "Sample Value": "5",
      "Size of Field": "N/A",
      "Related Documents": "Points Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Loyalty Program",
      "Field Name": "Rewards",
      "Field Description": "Available rewards",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Dropdown",
      "Sample Value": "$10 Gift Card",
      "Size of Field": "N/A",
      "Related Documents": "Rewards Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Loyalty Program",
      "Field Name": "Terms and conditions",
      "Field Description": "Terms and conditions of the program",
      "Mandatory / Optional": "Mandatory",
      "Data Type": "Checkbox",
      "Sample Value": true,
      "Size of Field": "N/A",
      "Related Documents": "Terms Document",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Loyalty Program",
      "Field Name": "Membership ID or Number",
      "Field Description": "Optional ID or Number for members",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "67890",
      "Size of Field": "10 characters",
      "Related Documents": "Membership Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Loyalty Program",
      "Field Name": "Membership Tier",
      "Field Description": "Membership level",
      "Mandatory / Optional": "Optional",
      "Data Type": "Dropdown",
      "Sample Value": "Gold",
      "Size of Field": "N/A",
      "Related Documents": "Tier Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Loyalty Program",
      "Field Name": "Description",
      "Field Description": "Additional information",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "Frequent flyer",
      "Size of Field": "100 characters",
      "Related Documents": "N/A",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Loyalty Program",
      "Field Name": "Points Redeem Option",
      "Field Description": "Options for redeeming points",
      "Mandatory / Optional": "Optional",
      "Data Type": "Dropdown",
      "Sample Value": "Gift Card",
      "Size of Field": "N/A",
      "Related Documents": "Redemption Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Loyalty Program",
      "Field Name": "Special Requests for Members",
      "Field Description": "Special requests like priority handling",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "Priority Handling",
      "Size of Field": "50 characters",
      "Related Documents": "Special Requests Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Loyalty Program",
      "Field Name": "Referral Code",
      "Field Description": "Code for referring new members",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "REF2023",
      "Size of Field": "10 characters",
      "Related Documents": "Referral Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Promotions and Discounts",
      "Field Name": "Coupon Code",
      "Field Description": "Code for applying a coupon",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "COUPON2023",
      "Size of Field": "10 characters",
      "Related Documents": "Coupon Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Promotions and Discounts",
      "Field Name": "Promotion Name",
      "Field Description": "Name of the promotion",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "Summer Sale",
      "Size of Field": "50 characters",
      "Related Documents": "Promotion Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Promotions and Discounts",
      "Field Name": "Discount Percentage",
      "Field Description": "Percentage of discount offered",
      "Mandatory / Optional": "Optional",
      "Data Type": "Number",
      "Sample Value": "20",
      "Size of Field": "N/A",
      "Related Documents": "Discount Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Promotions and Discounts",
      "Field Name": "Start Date",
      "Field Description": "Start date of the promotion",
      "Mandatory / Optional": "Optional",
      "Data Type": "Date",
      "Sample Value": "2023-06-01",
      "Size of Field": "N/A",
      "Related Documents": "Date Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Promotions and Discounts",
      "Field Name": "End Date",
      "Field Description": "End date of the promotion",
      "Mandatory / Optional": "Optional",
      "Data Type": "Date",
      "Sample Value": "2023-06-30",
      "Size of Field": "N/A",
      "Related Documents": "Date Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Promotions and Discounts",
      "Field Name": "Eligibility Criteria",
      "Field Description": "Criteria for eligibility",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "New Customers",
      "Size of Field": "100 characters",
      "Related Documents": "Eligibility Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Promotions and Discounts",
      "Field Name": "Promo Code or Coupon Code",
      "Field Description": "Alternative code for promotion",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "PROMO2023",
      "Size of Field": "10 characters",
      "Related Documents": "Promo Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Promotions and Discounts",
      "Field Name": "Loyalty Points Redemption",
      "Field Description": "Points needed for redemption",
      "Mandatory / Optional": "Optional",
      "Data Type": "Number",
      "Sample Value": "1000",
      "Size of Field": "N/A",
      "Related Documents": "Points Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Promotions and Discounts",
      "Field Name": "Gift Card Number",
      "Field Description": "Number of the gift card",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "GIFT1234",
      "Size of Field": "10 characters",
      "Related Documents": "Gift Card Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Promotions and Discounts",
      "Field Name": "Referral Code",
      "Field Description": "Code for referring new customers",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "REF2023",
      "Size of Field": "10 characters",
      "Related Documents": "Referral Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Promotions and Discounts",
      "Field Name": "Special Offer Selection",
      "Field Description": "Type of special offer",
      "Mandatory / Optional": "Optional",
      "Data Type": "Dropdown",
      "Sample Value": "Early Bird Discount",
      "Size of Field": "N/A",
      "Related Documents": "Special Offer Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Promotions and Discounts",
      "Field Name": "Description",
      "Field Description": "Additional information",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "Limited Time Offer",
      "Size of Field": "100 characters",
      "Related Documents": "N/A",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Feedback",
      "Field Name": "Overall Experience Rating",
      "Field Description": "Rating scale for overall experience",
      "Mandatory / Optional": "Optional",
      "Data Type": "Dropdown",
      "Sample Value": "4 stars",
      "Size of Field": "N/A",
      "Related Documents": "Feedback Policy",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Feedback",
      "Field Name": "Comments or Suggestions",
      "Field Description": "Field for additional comments",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "Great service!",
      "Size of Field": "200 characters",
      "Related Documents": "N/A",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Feedback",
      "Field Name": "Would you recommend us?",
      "Field Description": "Yes/No option for recommendation",
      "Mandatory / Optional": "Optional",
      "Data Type": "Radio Group",
      "Sample Value": "Yes",
      "Size of Field": "N/A",
      "Related Documents": "N/A",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Feedback",
      "Field Name": "What can we improve?",
      "Field Description": "Field for specifying areas for improvement",
      "Mandatory / Optional": "Optional",
      "Data Type": "Text",
      "Sample Value": "Faster delivery",
      "Size of Field": "200 characters",
      "Related Documents": "N/A",
      "Tool Tip": "",
      Prompt: "",
    },
    {
      Section: "Feedback",
      "Field Name": "Any specific issues encountered",
      "Field Description": "Dropdown for common issues",
      "Mandatory / Optional": "Optional",
      "Data Type": "Dropdown",
      "Sample Value": "Late delivery",
      "Size of Field": "N/A",
      "Related Documents": "Issue Policy",
      "Tool Tip": "",
      Prompt: "",
    },
  ],
};

export default database;
